from sqlalchemy import Column, Integer, String, Float, ForeignKey, Boolean, DateTime
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime

# Assuming Base is imported from the main models.py once merged
Base = declarative_base()

class UserProfile(Base):
    """
    Stores demographic and medical history data to identify failure trends.
    """
    __tablename__ = 'user_profiles'
    
    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True, nullable=False)
    
    # Metadata for Failure Trend Analysis
    body_geometry = Column(String)       # e.g., "long femurs"
    mobility_constraints = Column(String)# e.g., "tight ankles"
    medical_history = Column(String)     # e.g., "previous hamstring tear"
    
    feedbacks = relationship("UserFeedback", back_populates="user")

class UserFeedback(Base):
    """
    The core data structure for the Evergreen Data Loop. 
    Logs the user's mid-workout proprioception and form verification.
    """
    __tablename__ = 'user_feedback'
    
    id = Column(Integer, primary_key=True)
    tip_id = Column(Integer, nullable=False) # ForeignKey('tips.id') in unified schema
    user_id = Column(Integer, ForeignKey('user_profiles.id'), nullable=False)
    
    # Execution Tracking
    mediapose_form_pass = Column(Boolean, nullable=False, default=False)
    target_muscle_activated = Column(Boolean, nullable=False, default=False)
    pain_reported = Column(Boolean, nullable=False, default=False)
    
    # Did they perform the prescribed activation exercise first?
    activation_completed_id = Column(Integer, nullable=True) 
    
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    user = relationship("UserProfile", back_populates="feedbacks")

class DiagnosticCure(Base):
    """
    Stores hypothesized cures generated by the Diagnostic Decoding Engine
    to track their success rate over time against specific failure trends.
    """
    __tablename__ = 'diagnostic_cures'
    
    id = Column(Integer, primary_key=True)
    target_tip_id = Column(Integer, nullable=False) # ForeignKey('tips.id')
    
    # The condition being cured (e.g., "long femurs")
    failure_trend_condition = Column(String, nullable=False)
    
    # The prescribed cure (either an activation exercise or a semantic tip)
    prescribed_activation_id = Column(Integer, nullable=True)
    suggested_semantic_tip_id = Column(Integer, nullable=True)
    
    # Tracking success
    total_prescriptions = Column(Integer, default=0)
    successful_cures = Column(Integer, default=0) # Where user form passed & muscle activated
    
    @property
    def cure_success_rate(self) -> float:
        if self.total_prescriptions == 0:
            return 0.0
        return (self.successful_cures / self.total_prescriptions) * 100.0
